name: Create new empty release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Extracts the tag name
          name: ${{ github.ref_name }}  # Uses the tag name for the release name
          draft: false
          prerelease: false
