name: Create new empty release

on:
  push:
    tags:
      - '*'  # Only trigger on tag pushes
  workflow_dispatch:  # For manual trigger

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # This extracts the tag name from the ref
          release_name: ${{ github.ref_name }}  # Use the tag name for the release name
          draft: false
          prerelease: false
